# This is a basic workflow to help you get started with Actions

name: Dispatch
on:
  workflow_dispatch:
    inputs:
      test-name:
        required: true
jobs:
  build:
    name: build-${{ github.events.inputs.test-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
